---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ublue-niri
description: "Personal image with Niri, Waybar and other goodies."

base-image: ghcr.io/ublue-os/sericea-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ulysg/xwayland-satellite/repo/fedora-%OS_VERSION%/ulysg-xwayland-satellite-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://repo.librewolf.net/librewolf.repo
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      - micro
      - starship
      - niri
      - librewolf
      - SDL2
      - swww
      - swaync
    remove:
      - firefox
      - firefox-langpacks
      - sway
      - wofi
      - mako
      - alacritty
      - xarchiver

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Loupe
        - com.github.wwmm.easyeffects
        - it.mijorus.gearlever
      # remove:
      #   - 
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

