---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ublue-niri-noconfig
description: "Personal image with Niri and other goodies. No configs included."

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

modules:
  - from-file: common/repos.yml
  - from-file: common/common-packages.yml
  - from-file: common/basic-config.yml

  - type: signing 

