modules:
  - type: files
    files:
      - source: basics
        destination: /

  - type: systemd
    system:
      enabled:
        - greetd.service
    user:
      enabled:
        - swww-wallpaper.service

  - type: justfiles
    validate: false
    include:
      - config
